apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-start
spec:
  selector:
    matchLabels:
      app: go-start
  replicas: 1
  template:
    metadata:
      labels:
        app: go-start
    spec:
      containers:
      - name: go-start
        image: okteto.dev/go-start:latest
        ports:
        - containerPort: 8080